api_platform:
    title: 'PHARMA PROJECT'
    description: 'Backend for pharma project'
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 3
        pagination_items_per_page: 2
